# Build configuration for https://www.tea-ci.org
# (fork of Drone CI with MSYS2 support)
# http://docs.tea-ci.org/usage/overview/

build:
  image: teaci/msys32
  pull: true
  shell: msys32
  commands:
    - env
    - pacman -S --needed --noconfirm --noprogressbar zip
    - pacman -S --needed --noconfirm --noprogressbar python3
    - which python3
    - python3 -m this
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-i686-nsis
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-i686-gcc
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-i686-binutils
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-x86_64-nsis
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-x86_64-gcc
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-x86_64-binutils
    - ./styrene.sh --debug gtk3-examples.cfg
