# Build configuration for https://www.tea-ci.org
# (fork of Drone CI with MSYS2 support)
# http://docs.tea-ci.org/usage/overview/

build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - env
    - pacman -Sy --noconfirm --noprogressbar
    - ls -l /etc/pacman.d || true
    - cat /etc/pacman.d/mirrorlist.* || true
    - pacman -S --needed --noconfirm --noprogressbar zip
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-nsis
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-gcc
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-binutils
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-python3-pip
    - which python3
    - python3 -m this
    - which pip3
    - pip3 install .
    - styrene --colour=yes --output-dir=/tmp/test1 --no-exe --no-zip gtk3-examples.cfg

matrix:
  arch:
    - 64
    - 32
